export const KINTOBLOCKS = 'kintoblockmanager'
export const KINTOAPPS = 'kintoappmanager'
export const AUTH = 'auth'
export const WORKSPACES = 'workspaces'
export const DOCUMENTATION = 'documentation'
